name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Copy to Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          # repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "/" # App source code path relative to repository root
          #api_location: "api" # Api source code path relative to repository root - optional
          output_location: "/dist" # Built app content directory, relative to app_location - optional
          ###### End of Repository/Build Configurations ######
